### ISSUE TITLE
Mapping files on OSX

### ISSUE THREAD

**Issue by fritzem** [devkitPro/grit#10]
On windows, this operation will result in a `tileset.c`, `tileset.h`, `maps.c`, `maps.h`.
`./grit.exe picA.bmp picB.bmp -gt -gS -gB4 -m -mR4 -ftc -fa -o maps -O tileset -S set -W3`
>! PS> ./grit.exe picA.bmp picB.bmp -gt -gS -gB4 -m -mR4 -ftc -fa -o maps -O tileset -S set -W3
>! STATUS: ---grit v0.9.1 ---
>! STATUS: Shared-data run.
>! STATUS: Output file: 'maps'.
>! STATUS: Loading tile file.
>! WARNING:   No tilefile path. Tilefile load failed.
>! STATUS: Input file picA.bmp
>! STATUS: Output file: 'maps'.
>! STATUS: Started run at: 2022-10-26, 22:24:57
>! STATUS: Validating gr.
>! WARNING:   No explicit symbol name. In append mode, so using src title.
>! STATUS: Validation succeeded.
>! STATUS: Preparing data.
>! STATUS: Work-DIB creation.
>! STATUS: Work-DIB creation complete: 16x16@8.
>! STATUS:   Performing tile reduction: unique tiles; flip; palswap;
>! STATUS: Map preparation complete.
>! STATUS: Graphics preparation.
>! STATUS:   Bitpacking: 8 -> 4.
>! STATUS: Graphics preparation complete.
>! STATUS: Palette preparation.
>! STATUS: Palette preparation complete.
>! STATUS: Data preparation complete.
>! STATUS: Export to C: picA into maps.c .
>! STATUS: Run completed :).
>! STATUS: Input file picB.bmp
>! STATUS: Output file: 'maps'.
>! STATUS: Started run at: 2022-10-26, 22:24:57
>! STATUS: Validating gr.
>! WARNING:   No explicit symbol name. In append mode, so using src title.
>! STATUS: Validation succeeded.
>! STATUS: Preparing data.
>! STATUS: Work-DIB creation.
>! STATUS: Work-DIB creation complete: 64x8@8.
>! STATUS:   Performing tile reduction: unique tiles; flip; palswap;
>! STATUS:   Using external tileset.
>! STATUS: Map preparation complete.
>! STATUS: Graphics preparation.
>! STATUS:   Bitpacking: 8 -> 4.
>! STATUS: Graphics preparation complete.
>! STATUS: Palette preparation.
>! STATUS: Palette preparation complete.
>! STATUS: Data preparation complete.
>! STATUS: Export to C: picB into maps.c .
>! STATUS: Run completed :).
>! STATUS: Saving tile file: `(null)'.
>! WARNING:   No tilefile path. Tilefile save failed.
>! STATUS: Output file: 'maps'.
>! STATUS: Validating gr.
>! STATUS: Validation succeeded.
>! STATUS: Graphics preparation.
>! STATUS:   Bitpacking: 8 -> 4.
>! STATUS: Graphics preparation complete.
>! STATUS: Palette preparation.
>! STATUS: Palette preparation complete.
>! STATUS: Export to C: set into tileset.c .
>! STATUS: Conversion finished.
>! STATUS: Done!

On macOS, this operation will only result in a `tileset.c` and `tileset.h`.
`grit picA.bmp picB.bmp -gt -gS -gB4 -m -mR4 -ftc -fa -o maps -O tileset -S set -W3`
>! STATUS: ---grit v0.9.1 ---
>! STATUS: Shared-data run.
>! STATUS: Output file: 'maps'.
>! STATUS: Loading tile file.
>! WARNING:   No tilefile path. Tilefile load failed.
>! STATUS: Input file picA.bmp
>! STATUS: Output file: 'maps'.
>! STATUS: Started run at: 2022-10-26, 23:01:21
>! STATUS: Validating gr.
>! WARNING:   No explicit symbol name. In append mode, so using src title.
>! STATUS: Validation succeeded.
>! STATUS: Preparing data.
>! STATUS: Work-DIB creation.
>! STATUS: Work-DIB creation complete: 16x16@8.
>! STATUS:   Performing tile reduction: unique tiles; flip; palswap; 
>! STATUS: Map preparation complete.
>! STATUS: Graphics preparation.
>! STATUS:   Bitpacking: 8 -> 4.
>! STATUS: Graphics preparation complete.
>! STATUS: Palette preparation.
>! STATUS: Palette preparation complete.
>! STATUS: Data preparation complete.
>! STATUS: Export to C: picA into maps.c .
>! STATUS: Run completed :).
>! STATUS: Input file picB.bmp
>! STATUS: Output file: 'maps'.
>! STATUS: Started run at: 2022-10-26, 23:01:21
>! STATUS: Validating gr.
>! WARNING:   No explicit symbol name. In append mode, so using src title.
>! STATUS: Validation succeeded.
>! STATUS: Preparing data.
>! STATUS: Work-DIB creation.
>! STATUS: Work-DIB creation complete: 64x8@8.
>! STATUS:   Performing tile reduction: unique tiles; flip; palswap; 
>! STATUS:   Using external tileset.
>! STATUS: Map preparation complete.
>! STATUS: Graphics preparation.
>! STATUS:   Bitpacking: 8 -> 4.
>! STATUS: Graphics preparation complete.
>! STATUS: Palette preparation.
>! STATUS: Palette preparation complete.
>! STATUS: Data preparation complete.
>! STATUS: Export to C: picB into maps.c .
>! STATUS: Run completed :).
>! STATUS: Saving tile file: `(null)'.
>! WARNING:   No tilefile path. Tilefile save failed.
>! STATUS: Output file: 'maps'.
>! STATUS: Validating gr.
>! STATUS: Validation succeeded.
>! STATUS: Graphics preparation.
>! STATUS:   Bitpacking: 8 -> 4.
>! STATUS: Graphics preparation complete.
>! STATUS: Palette preparation.
>! STATUS: Palette preparation complete.
>! STATUS: Export to C: set into tileset.c .
>! STATUS: Conversion finished.
>! STATUS: Done!

I've tested this on both macOS 12.6 and 11.6.4. Intel and M1. Running the command multiple times will result in the tileset files being deleted and recreated.

**Comment by WinterMute** [comment]
Fixed with https://github.com/devkitPro/grit/commit/5dbfc2b585f9e283135a746862e1878b14221cea thanks to @endrift

0.9.2 released with fix.
