### ISSUE TITLE
no config.yml

### ISSUE THREAD

**Issue by joe13206** [devkitPro/grit#13]
grit.rb:47:in `initialize': No such file or directory @ rb_sysopen - c:/custom/bin/.grit/config.yml (Errno::ENOENT)
        from grit.rb:47:in `open'
        from grit.rb:47:in `get_config'
        from grit.rb:142:in `proceed'
        from grit.rb:179:in `<main>'
        
please help if you can, i dont know if i set it up right, thank you!

**Comment by WinterMute** [comment]
No idea what this is, sorry. Whatever it is has nothing to do with us, we only supply software via pacman.
