### ISSUE TITLE
Huffman tiles compression doesn't work

### ISSUE THREAD

**Issue by GValiente** [devkitPro/grit#4]
[LZ77 test](https://github.com/devkitPro/grit/files/5715483/lz77_test.zip).
[Huffman test](https://github.com/devkitPro/grit/files/5715484/huffman_test.zip).

The two tests above show a sprite which tiles have been compressed with grit: the first one uses LZ77 compression and the second one uses Huffman compression.

While the first one works as expected, the second one shows garbage on the screen.

**Comment by AntonioND** [comment]
While fixing it may be a problem (apparently most compressors of Huffman for the GBA have issues, it's not trivial) I think that at least it should be disabled (or removed from the command line options and help).
