### ISSUE TITLE
Huffman compression asserts crash grit

### ISSUE THREAD

**Issue by GValiente** [devkitPro/grit#9]
grit 0.9.0 is built with asserts enabled.

With some files, huffman compression asserts crash grit with this message:
`Assertion failed: memcmp (src->data, test.data (), huff.size ()) == 0, file libgrit/cprs_huff.cpp, line 693`

If you disable those asserts huffman compression seems to work fine.

The *.bmp inside [this zip](https://github.com/devkitPro/grit/files/9351844/inverse.zip) crashes grit when processed as a 4bpp sprite.

**Comment by mtheall** [comment]
I dunno encoding the Huffman tree has been a royal pita. In this specific case LZSS ends up less than half the size so I would just use that.

**Comment by GValiente** [comment]
Can't you just disable asserts for huffman compression on release builds?

Disabling them makes grit faster and avoids crashes, and for other images (I don't have any of them at hand) compression worked fine even if the assert was triggered, so maybe what's wrong is the assert, not the compression itself.

**Comment by GValiente** [comment]
Confirmed.

This example project crashes grit, but if you disable Huffman compression asserts it works fine.

[huffman_test.zip](https://github.com/devkitPro/grit/files/9359607/huffman_test.zip)

**Comment by GValiente** [comment]
With grit 0.9.1, Huffman compression works with everything I have tried.

Thanks a lot.
